"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import HomeHeader from "./_components/HomeHeader";
import NavBar from "./_components/Navbar";
import React, { useState, useEffect } from 'react';
import { Toaster } from "react-hot-toast";

import { UserProvider, useUser } from "../context/UserContext";
import { Faq } from "./_components/Faq";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const { userLogin, setUserLogin } = useUser();
  // const [userlogin, setUserLogin] = useState(false);
  // const [user, setUser] = useState(false);
  // const [userrole, setUserRole] = useState("doctor");
  const { userLogin, setUserLogin, user, setUser, userrole, setUserRole } = useUser();


  // console.log('userlogin:', userLogin);
  // console.log('userrole:', userrole);
  // console.log('user:', user);
  // console.log('setUserLogin:', setUserLogin);
  // useEffect(() => {
  //   const token = window.localStorage.getItem('token');
  //   if (token) {
  //     // Token found, set authentication state or perform any necessary actions
  //     // setUserLogin(true);
  //   }
  // }, []);
  // useEffect(() => {
  //   const token = window.localStorage.getItem('token');
  //   if (token) {
  //     // Token found, set authentication state or perform any necessary actions
  //     setUserLogin(true);
  //   }
  // }, [userLogin]);
  return (
    <UserProvider>
      <html lang="en" >
        <body className="w-full" >
          <div className="w-full">
            {/* <p className="pt-32">hi</p>./ */}
            {/* <NavBar user={user} setUser={setUser} userrole={userrole} setUserRole={setUserRole} userlogin={userlogin} setUserLogin={setUserLogin} /> */}
            <NavBar />
            <Toaster position="top-center" />
            {/* {children && React.cloneElement(children, {
              user,
              setUser,
              userrole,
              setUserRole,
              userlogin,
              setUserLogin,
            })} */}
            {children}
          </div>
          {/* <Faq /> */}
          <Footer />
        </body>
      </html>
    </UserProvider>
  );
}
