"use client"
import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import HomeHeader from "./_components/HomeHeader";
import NavBar from "./_components/Navbar";
import React from 'react';
import { Toaster } from "react-hot-toast";

import { UserProvider, useUser } from "../context/UserContext";
import { Faq } from "./_components/Faq";
import Footer from "./_components/Footer";
import Loading from "./_components/Loading/Loading";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { userLogin, setUserLogin, user, setUser, userrole, setUserRole } = useUser();

  // if (loading) {
  //   return <Loading />;
  // }

  return (
    <>
      <Head>
        <title>Rk Clinic jaipur</title>
        <meta name="description" content="Your project description" />
        <link rel="icon" href="/profile.jpg" /> {/* Reference your favicon here */}
      </Head>
      <UserProvider>
        <html lang="en" >
          <body className="w-full" >
            <div className="w-full">
              <NavBar />
              <Toaster position="top-center" />
              {children}
            </div>
            <Footer />
          </body>
        </html>
      </UserProvider>
    </>
  );
}
